# Python Basics

## Your first Python code
It's time to run your first Python code!

Head to the code and hit the run code button to see the output.

* Hit the run code button to see the output of 
```python
print(5 / 8)
```

In [1]:
print(5/8)

0.625


## Any comments?
You can also add **comments** to your Python scripts. Comments are important to make sure that you and others can understand what your code is about and do not run as Python code.

They start with `#` tag. See the comment in the editor, `#` Division; now it's your turn to add a comment!

* Replace ____ with the comment
* \# Addition

In [2]:
# Division
print(5 / 8)
#Addition
print(7 + 10)

0.625
17


## Python as a calculator
Python is perfectly suited to do basic calculations. It can do addition, subtraction, multiplication and division.

The code in the script gives some examples.

Now it's your turn to practice!

### Instructions
* Print the sum of `4 + 5`.
* Print the result of subtracting `5 from 5`.
* Print the result of multiplying `3 by 5`.
* Print the result of dividing `10 by 2`.

In [3]:
# Addition
print(4+5)

# Subtraction
print(5-5)

# Multiplication
print(3*5)

# Division
print(10/2)

9
0
15
5.0


### Variable Assignment
In Python, a variable allows you to refer to a value with a name. To create a variable `x` with a value of `5`, you use `=`, like this example:
```python
x = 5
```

You can now use the name of this variable, `x`, instead of the actual value, `5`.

Remember, `=` in Python means assignment, it doesn't test equality! Try it in the exercise by replacing `____` with your code.

#### Instructions
* Create a variable savings with the value of 100.
* Check out this variable by typing print(savings) in the script.



In [4]:
savings = 100

# Print out savings
print(savings)

100


### Calculations with variables
You've now created a savings variable, so let's start saving!

Instead of calculating with the actual values, you can use variables instead.

How much money would you have saved four months from now, if you saved $10 each month?

#### Instructions

* Create a variable `monthly_savings`, equal to `10` and `num_months`, equal to `4`.
* Multiply `monthly_savings` by `num_months` and assign it to `new_savings`.
* Print the value of `new_savings`.

### Other variable types
In the previous exercise, you worked with the integer Python data type:

* `int`, or integer: a number without a fractional part. `savings`, with the value `100`, is an example of an integer.
Next to numerical data types, there are three other very common data types:

* `float`, or floating point: a number that has both an integer and fractional part, separated by a point. `1.1`, is an example of a float.
* `str`, or string: a type to represent text. You can use single or double quotes to build a string.
* `bool`, or boolean: a type to represent logical values. It can only be `True` or `False` (the capitalization is important!).

#### Instructions

* Create a new float, `half`, with the value `0.5`.
* Create a new string, `intro`, with the value `"Hello! How are you?"`.
* Create a new boolean, `is_good`, with the value `True`.

In [ ]:
# Create a variable half
half = 0.5

# Create a variable intro
intro = "Hello! How are you?"

# Create a variable is_good
is_good = True

### Operations with other types
Variables come in different types in Python. You can see the type of a variable by using `type()`. For example, to see type of a, execute: `type(a)`.

Different types behave differently in Python. When you sum two strings, for example, you'll get different behavior than when you sum two integers or two booleans.

Time for you to test this out.

Instructions 1/2

* Add `savings` and `new_savings` and assign it to `total_savings`.
* Use `type()` to print the resulting type of `total_savings`.

In [7]:
savings = 100
new_savings = 40

# Calculate total_savings using savings and new_savings
total_savings = savings + new_savings
print((type(total_savings)))
print(total_savings)

<class 'int'>
140


#### Instructions 2/2

* Calculate the sum of `intro` and intro and assign the result to `doubleintro`.
* Print out `doubleintro`. Did you expect this?

In [12]:
intro = "Hello! How are you?"

# Assign sum of intro and intro to doubleintro
doubleintro = intro + intro
print(type(doubleintro))
# Print out doubleintro
print(doubleintro)

<class 'str'>
Hello! How are you?Hello! How are you?


# Python Lists
Learn to store, access, and manipulate data in lists: the first step toward efficiently working with huge amounts of data.

## Create a list
A list is a `compound data type`; you can group values together, like this:

```python
a = "is"
b = "nice"
my_list = ["my", "list", a, b]
```

After measuring the height of your family, you decide to collect some information on the house you're living in. The areas of the different parts of your house are stored in separate variables in the exercise.

### Instructions
* Create a list, `areas`, that contains the area of the hallway (`hall`), kitchen (`kit`), living room (`liv`), bedroom (`bed`) and bathroom (`bath`), in this order. Use the predefined variables.
* Print `areas` with the `print()` function.

In [10]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall, kit, liv, bed, bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


## Create lists with different types
Although it's not really common, a list can also contain a mix of Python types including strings, floats, and booleans.

You're now going to add the room names to your list, so you can easily see both the room name and size together.

Some of the code has been provided for you to get you started. Pay attention here! `"bathroom"` is a string, while bath is a variable that represents the float `9.50` you specified earlier.

### Instructions

* Finish the code that creates the `areas` list. Build the list so that the list first contains the name of each room as a string and then its area. In other words, add the strings `"hallway"`, `"kitchen"` and `"bedroom"` at the appropriate locations.
* Print `areas` again; is the printout more informative this time?

In [11]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]



## List of lists
As a data scientist, you'll often be dealing with a lot of data, and it will make sense to group some of this data.

Instead of creating a list containing strings and floats, representing the names and areas of the rooms in your house, you can create a list of lists.

Remember: `"hallway"` is a string, while `hall` is a variable that represents the float `11.25` you specified earlier.

### Instructions

* Finish the list of lists so that it also contains the bedroom and bathroom data. Make sure you enter these in order!
* Print out `house`; does this way of structuring your data make more sense?

In [13]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# House information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
        ["bedroom", bed],
        ["bathroom", bath]]

# Print out house
print(house)

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]


## Subset and conquer
Subsetting Python lists is a piece of cake. Take the code sample below, which creates a list `x` and then selects `"b" `from it. Remember that this is the second element, so it has index `1`. You can also use `negative indexing`.

```python
x = ["a", "b", "c", "d"]
x[1]
x[-3] # same result!
```

Remember the `areas` list from before, containing both strings and floats? Its definition is already in the script. Can you add the correct code to do some Python subsetting?

### Instructions

* Print out the second element from the `areas` list (it has the value `11.25`).
* Subset and print out the last element of `areas`, being `9.50`. Using a negative index makes sense here!
* Select the number representing the area of the living room (`20.0`) and print it out.

In [16]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[-5])

11.25
9.5
20.0


## Slicing and dicing
Selecting single values from a list is just one part of the story. It's also possible to slice your list, which means selecting multiple elements from your list. Use the following syntax:

```python
my_list[start:end]
```

The `start` index will be included, while the `end` index is `not`. However, it's also possible not to specify these indexes. If you don't specify the `start` index, Python figures out that you want to start your slice at the beginning of your list.

### Instructions

* Use slicing to create a list, `downstairs`, that contains the first 6 elements of `areas`.
* Create `upstairs`, as the last `4` elements of areas. This time, simplify the `slicing` by omitting the `end` index.
* Print both `downstairs` and `upstairs` using `print()`.

In [19]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[6:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


### Exercise
#### Subsetting lists of lists
A Python list can also contain other lists.

To subset lists of lists, you can use the same technique as before: square brackets. This would look something like this for a list, house:

```python
house[2][0]
```
#### Instructions

Subset the `house` list to get the float `9.5`.

In [23]:
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathroom", 9.50]]

# Subset the house list
house[4][1]


9.5

## Replace list elements
To replace list elements, you subset the list and assign new values to the subset. You can select single elements or you can change entire list slices at once.

For this and the following exercises, you'll continue working on the `areas` list that contains the names and areas of different rooms in a house.


### Instructions

* Update the area of the bathroom to be `10.50` square meters instead of `9.50` using negative indexing.
* Make the `areas` list more trendy! Change `"living room"` to `"chill zone"`. Don't use negative indexing this time.

In [26]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area

areas[-1] = 10.50
# Change "living room" to "chill zone"
areas[4] = "chill zone"
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]



## Extend a list
If you can change elements in a list, you sure want to be able to add elements to it, right? You can use the `+` operator:

```python
x = ["a", "b", "c", "d"]
y = x + ["e", "f"]
```
You just won the lottery, awesome! You decide to build a poolhouse and a garage. Can you add the information to the `areas` list?


### Instructions

* Use the `+` operator to paste the list `["poolhouse", 24.5]` to the end of the `areas` list. Store the resulting list as `areas_1`.
* Further extend `areas_1` by adding data on your garage. Add the string `"garage"` and float `15.45`. Name the resulting list `areas_2`.

In [29]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]
